const CREATE_EXPIRE_MONTH = 'CREATE_EXPIRE_MONTH'
const CREATE_EXPIRE_YEAR = 'CREATE_EXPIRE_YEAR'
const CREATE_OWNER_NAME = 'CREATE_OWNER_NAME'
const CREATE_CARD_CVC = 'CREATE_CARD_CVC'
const CREATE_CARD_PASSWORD1 = 'CREATE_CARD_PASSWORD1'
const CREATE_CARD_PASSWORD2 = 'CREATE_CARD_PASSWORD2'

export {
  CREATE_EXPIRE_MONTH,
  CREATE_EXPIRE_YEAR,
  CREATE_OWNER_NAME,
  CREATE_CARD_CVC,
  CREATE_CARD_PASSWORD1,
  CREATE_CARD_PASSWORD2,
}
