export const CHANGE_CARD = {
  NUMBERS: 'CHANGE_CARD_NUMBERS',
  EXP_DATE: 'CHANGE_CARD_EXPIRATION_DATE',
  OWNER: 'CHANGE_CARD_OWNER',
  CVC: 'CHANGE_CARD_CVC',
  PW: 'CHANGE_CARD_PASSWORD',
  COMPANY: 'SELECT_CARD_COMPANY',
  NICKNAME: 'CHANGE_CARD_NICKNAME',
  ERROR: 'SET_ERROR',
  ID: 'SET_CARD_ID',
  INIT: 'INITIALIZE_CARD_INFO',
};
