export const DISPLAY_CARD_NUMBER_COUPLER = '-';
export const DISPLAY_EXPIRATION_DATE_COUPLER = '/';
export const DISPLAY_SECURITY_CHARACTER = '•';
export const DISPLAY_MAX_LENGTH_CARD_OWNER_NAME = 3;
