export const MONTH_RANGE = {
  min: 1,
  max: 12,
};

export const CARD_EXPIRE_DATE_MAX_LENGTH = 6;

export const CARD_OWNER_NAME_MAX_LENGTH = 30;

export const CVC_NUMBER_MAX_LENGTH = 3;

export const CARD_INPUT_VARIABLES = {
  NUMBER_MAX_LENGTH: 16,
  PARTIAL_NUMBER_MAX_LENGTH: 4,
  MAX_MONTH: 12,
  MIN_MONTH: 1,
  OWNER_NAME_MAX_LENGTH: 3,
  CVC_NUMBER_MAX_LENGTH: 3,
};
