export const CARD_INPUT_VARIABLES = {
  NUMBER_MAX_LENGTH: 16,
  PARTIAL_NUMBER_MAX_LENGTH: 4,
  DATE_MAX_LENGTH: 2,
  MAX_MONTH: 12,
  MIN_MONTH: 1,
  OWNER_NAME_MAX_LENGTH: 30,
  CVC_NUMBER_MAX_LENGTH: 3,
  PARTIAL_PASSWORD_MAX_LENGTH: 1,
  CARD_NAME_MAX_LENGTH: 10,
};
